receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 10s
          static_configs:
            - targets: ['192.168.101.17:9090']

exporters:
  otlphttp:
    endpoint: "https://6kyjm29wa6.execute-api.us-east-1.amazonaws.com/"
    headers:
      "x-api-key": "${API_KEY}" # API Key will be passed as an environment variable
  
  debug:
    verbosity: detailed

processors:
  batch: {}
  transform:
    metric_statements:
      - context: metric
        statements:
          - "keep_metrics(metric.type_str == \"Gauge\" or metric.type_str == \"Sum\")"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch, transform]
      exporters: [otlphttp, debug]