receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 10s
          static_configs:
            - targets: ['192.168.101.17:9090']
  filelog:
    include:
      - /var/log/syslog
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: "https://2i5jbul6bajunwmqxtqjcwmbfu0ockfz.lambda-url.us-east-1.on.aws/"
    headers:
      "x-api-key": "${API_KEY}" # API Key will be passed as an environment variable

  debug:
    verbosity: detailed

processors:
  batch: {}
  filter:
    metrics:
      metric:
        - 'type == "Histogram"'
        - 'type == "ExponentialHistogram"'
        - 'type == "Summary"'

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch, filter]
      exporters: [otlphttp, debug]

    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [otlphttp, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
