apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CLUSTER_ID
          value: {{ .Values.clusterId | quote }}
        - name: CENTRAL_API_URL
          value: {{ .Values.centralApiUrl | quote }}
        - name: API_KEY
          value: {{ .Values.apiKey | quote }}
        - name: PROMETHEUS_URL
          value: "http://prometheus-operated.monitoring.svc:9090"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-metrics
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Chart.Name }}