# Default values for edge-agent
clusterId: "default-cluster"
centralApiUrl: "http://localhost:8000"
apiKey: "change-me-in-production"

image:
  repository: your-ecr-repo/edge-agent
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: edge-agent

rbac:
  create: true

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"