name: Terraform Plan and Apply

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infrastructure/terraform/**'

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.0

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        cd infrastructure/terraform
        terraform init

    - name: Terraform Format
      run: |
        cd infrastructure/terraform
        terraform fmt -check

    - name: Terraform Validate
      run: |
        cd infrastructure/terraform
        terraform validate

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: |
        cd infrastructure/terraform
        terraform plan -input=false

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cd infrastructure/terraform
        terraform apply -auto-approve -input=false
      env:
        TF_CLI_ARGS_apply: -auto-approve -input=false