name: Deploy Infrastructure

on:
  workflow_run:
    workflows: ["Build and Deploy Central Brain Lambda"]
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.0

jobs:
  terraform-deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    defaults:
      run:
        shell: bash
        working-directory: infrastructure/terraform
    env:
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TF_VAR_api_key: ${{ secrets.API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Download Lambda Zip Key Artifact
      if: github.event_name == 'workflow_run'
      uses: actions/download-artifact@v4
      with:
        name: central-brain-lambda-zip-key
        path: infrastructure/terraform/artifacts
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Read Lambda Zip Key
      id: lambda_key
      run: |
        if [ -f infrastructure/terraform/artifacts/lambda_zip_key.txt ]; then
          echo "key=$(cat infrastructure/terraform/artifacts/lambda_zip_key.txt)" >> $GITHUB_OUTPUT
        else
          # This default is a fallback for manual runs, but a real key is required for a successful apply.
          echo "key=placeholder.zip" >> $GITHUB_OUTPUT
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      id: init
      run: |
        terraform init \
          -backend-config="bucket=ai-devops-platform-tfstate-${{ secrets.AWS_ACCOUNT_ID }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="encrypt=true"

    - name: Terraform Apply
      id: apply
      run: |
        terraform apply -auto-approve -input=false -var="lambda_zip_key=${{ steps.lambda_key.outputs.key }}"